### ISSUE TITLE
Post clustering - closest organism ending up in a weird mixed cluster even though the scores say otherwise

### ISSUE THREAD

**Issue by TealFurnholm** [MrOlm/drep#84] opened 2020-07-03 17:27 UTC
Greetings!

I clustered several hundred single-sample bins with multiple strains of closely-related fully sequenced/completed reference genomes (using complete genomes to help dRep cluster the incomplete bins). 
> comics dRep cluster dRep/ -p 40 -pa 0.5 -g ./*.fa &> dRep_cluster_with_ref.log

While this approach seems to work very well in most cases, putting different genera into different Mash clusters (50% id) and then separating the species/strains into different mummer/sub-clusters (99% gANI). 
BUT I noticed that there is a really weird Mash cluster with VERY different species in it:
**Reference Genome | cluster**
JANTHINOBACTERIUM_LIVIDUM_MEG1.FA | 2_1
RHODANOBACTER_SPATHIPHYLLI_B39.FA | 2_2
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.FA | 2_3
STENOTROPHOMONAS_MALTOPHILIA_JV3.FA | 2_4

I checked the scores in the Mdb.csv and they should not have ended up in that cluster.
For example, looking at "STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS" reference genome - it is most close to Staphylococcus warneri based on the similarity (bottom of the list).

> grep -P "^STAPHYLOCOCCUS_PETTENKOFERI.*\.[123456789]\d+$" Mdb.csv | sort -t"," -k4,4n

genome1,genome2,dist,similarity
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,ALL-CLU_158_7_NR_contigs.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,ALL-CLU_158_9_NR_contigs.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,ALL-CLU_160_0_NR_contigs.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,JANTHINOBACTERIUM_LIVIDUM_MEG1.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,RHODANOBACTER_SPATHIPHYLLI_B39.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STENOTROPHOMONAS_MALTOPHILIA_JV3.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_EPIDERMIDIS_ATCC_14990.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_EPIDERMIDIS_BPH0662.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_EPIDERMIDIS_BVS058A4.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_EPIDERMIDIS_NBRC_100911.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_EPIDERMIDIS_VCU071.fa,0.295981,0.704019
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,ALL-CLU_158_23_NR_contigs.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,ALL-CLU_158_2_NR_contigs.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,ALL-CLU_158_8_NR_contigs.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_AUREUS_NCTC_8325.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_CAPITIS_C87.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_CAPITIS_H36.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_CAPITIS_QN1.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_CAPITIS_AYP1020.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_CAPITIS_TW2795_DNA.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_SACCHAROLYTICUS_11807.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_SP_HMSC060D01.fa,0.263022,0.736978
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_HOMINIS_K1.fa,0.243761,0.756239
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_SP_HMSC070D05.fa,0.243761,0.756239
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_CAPRAE_M23864_W1.fa,0.23010999,0.76989
STAPHYLOCOCCUS_PETTENKOFERI_FDAARGOS_288.fa,STAPHYLOCOCCUS_WARNERI_NCTC11044.fa,0.23010999,0.76989

Why is it putting S. pettenkoferi into a cluster with those other weird genomes like Rhodanobacter instead of with the other Staphylococcus that it is more similar to? 76% is certainly high enough to go into the same Mash cluster.

Thank you!

**Comment by MrOlm** [comment] 2020-07-06 23:26
Hello,

Almost certainly the reason this is happening has to do with the way hierarchical clustering is done. You can see visualize this by running the analyze module to generate a dendrogram of the primary clustering (though if you have too many genomes this can get too big to be visualized).

By default, hierarchical clustering is performed in dRep using average linkage (https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) which can result in things like you're seeing. If you want all cases where two genomes are over your thresholds to be in the same cluster, you can run it in single mode (--clusterAlg single). The problem is that this can create big clusters- for example if A is similar to B, and B is similar to C, but A and C are not similar, what do you do? In single mode A, B, and C will be in the same cluster, and in average mode some averaging is done to try and handle this.

dRep can use any method of linkage listed at the following webpage by using the --clusterAlg argument: https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html

Hope this helps!
-Matt

**Closed** 2020-07-13 20:58 UTC
