### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by MeggyC** [MrOlm/drep#76] opened 2020-04-16 23:57 UTC
Hi there, 

I've been using the cluster module alone to dereplicate a set of putative viral contigs (>2kbp). I set the minimum ANI at 0.95 and the nc at 0.8 (flags: -nc 0.8 -sa 0.95), as per the literature. 

I have merged the Cdb and Ndb output and it shows that when, for example, virus 1 is compared to virus 2, the alignment ani is of 99%, the alignment coverage of virus 1 is of 61%, and the alignment coverage of virus 2 is of 99%. They are both assigned to secondary cluster 1_1. This makes sense: virus one is a longer sequence than virus 2, and it is likely that virus 2 is a poorly assembled fragment of virus 1. However, when virus 3 is compared to virus 2, the alignment ani is of 99%, the alignment coverage of virus 1 is of 65%, and the alignment coverage of virus 2 is of 99%. This is pretty much the same situation as before in terms of metrics. However, here they are assigned to different secondary clusters 1_1, and 1_2.
![image](https://user-images.githubusercontent.com/48115052/79517393-687f2e00-8091-11ea-9e73-14252c36d60e.png)

Why is virus 3 not clustered with virus 2? Is there a way to change clustering criteria so that they will be clustered together? 

Additionally, I have a large amount of viral genomes that share > 95% ani, and the alignment covers  above 80% of both genomes. However, they have been placed in separate clusters: surely these should be collapsed into the same cluster?  

Thanks :)

**Comment by MrOlm** [comment] 2020-04-17 18:48
Hello,

Great question. A couple of things here:

1) This doesn't seem to be a problem with the example you gave, but something that can put similar genomes into different clusters is if they end up in different *primary* clusters. Primary clusters are determined using Mash, which is really fast, but not very accurate for genomes of different sizes. You can avoid this problem entirely by using the flag `--skip_Mash`, but this will increase run-time. You can also set a lower primary clustering threshold `-pa` to something like 0.5, which will also increase run-time but not by as much.

2) Almost certainly the reason this is happening has to do with the way hierarchical clustering is done. You can see visualize this by running the `analyze` module to generate plots for the dendrograms (plot number 2 is what you want). 

By default, hierarchical clustering is performed in dRep using `average` linkage (https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) which can result in things like you're seeing. If you want all cases where two genomes are over your thresholds to be in the same cluster, you can run it in `single` mode (`--clusterAlg single`). The problem is that this can create big clusters- for example if A is similar to B, and B is similar to C, but A and C are not similar, what do you do? In `single` mode A, B, and C will be in the same cluster, and in `average` mode some averaging is done to try and handle this.

dRep can use any method of linkage listed at the following webpage by using the `--clusterAlg` argument: https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html

Hope this helps!
-Matt

**Comment by MeggyC** [comment] 2020-04-20 00:50
Hi there Matt, 

Thanks for responding, that's really helpful. The dendrograms and the MDS are really helpful. By looking at my results, the instances in which high ani high coverage pairs are clustered separately seem to arise from the hierarchial clustering, but it's definitely good to know about Mash. 

Thanks for your help!

**Closed** 2020-04-20 16:27 UTC
